### ISSUE TITLE
Doesn't work with d5300

### ISSUE THREAD

**Issue by viktor02** [puhitaku/mtplvcap#12]
Hi I am using your program with nikon d5300 however it prints errors and no image from the camera in the browser.
What could be the error?
Also, during startup, the program take a picture(judging by the sound), but after some time a timeout error appears and errors begin to appear
I also tried the nikon webcam utility, but I also have no camera image in it.

video: https://drive.google.com/file/d/1eRFpiXMSmE6y80bg5K282pCUKTHyPRKI/view?usp=sharing

**Comment by puhitaku** [comment]
It seems like something is interfering with the communication between mtplvcap and the D5300.

Is there a utility related to backups like Dropbox, NAS backup tools, etc.? One of my users reported that Qsync (QNAP's backup utility) was interfering with mtplvcap on his/her computer.

**Comment by puhitaku** [comment]
@viktor02 sorry for inactivity,

It seems like something is interfering with the communication between mtplvcap and the D5300.

Is there a utility related to backups like Dropbox, NAS backup tools, etc.? One of my users reported that Qsync (QNAP's backup utility) was interfering with mtplvcap on his/her computer.

**Comment by viktor02** [comment]
> 
> 
> @viktor02 sorry for inactivity,
> 
> It seems like something is interfering with the communication between mtplvcap and the D5300.
> 
> Is there a utility related to backups like Dropbox, NAS backup tools, etc.? One of my users reported that Qsync (QNAP's backup utility) was interfering with mtplvcap on his/her computer.

Now I tried on reinstalled Windows - the error is different:
![изображение](https://user-images.githubusercontent.com/19672960/101072075-8365ca80-35ae-11eb-9ff2-60690993d599.png)

It looks like my Chinese cable was broken :(

**Comment by viktor02** [comment]
Also after reboot, error same as first post

**Comment by puhitaku** [comment]
I guess it's an environmental issue that is identical to [this comment thread](https://www.reddit.com/r/Nikon/comments/hzcue6/software_to_turn_your_nikon_cam_into_a_webcam_on/gc90yo5/). I hope there's no software interfering with mtplvcap as you've re-installed Windows...

There's nothing more to suggest you to do but... how about changing the USB port to connect? Does other alternative software like Nikon Webcam Utility work?

**Comment by puhitaku** [comment]
Going to close this issue. If you suffer additional issue, please open this or a new issue.

**Comment by viktor02** [comment]
Hi! I managed to find the original cable from nikon d750 and it worked! Nikon d750 has a resolution of 1024x768 and d5300 has 640x424. It's sad, but apparently these are Nikon's problems.

**Comment by puhitaku** [comment]
@viktor02 That's great! Do you mean that you successfully used mtplvcap with D750? I'm facing issue #25 and the author says s/he could not use mtplvcap with D750. If you did, it's a big leap! I'd like to add D750 to "confirmed cameras" list with your name alongside.

**Comment by viktor02** [comment]
Yes, it works, but as I understand it, it has Linux, and I ran it from Windows, maybe this is the problem

**Comment by puhitaku** [comment]
Thanks for your cooperation, from the bottom of my heart

**Comment by viktor02** [comment]
Sorry, I put it wrong when I talked about resolution. On nikon d750, I get the same error as here #25
