### ISSUE TITLE
D7100 image is really dark ISO is 0

### ISSUE THREAD

**Issue by wifiuk** [puhitaku/mtplvcap#13]
image is really dark and when you go on the web-browser the ISO is set to 0.

When you change it, it basically crashes and nothing else works from that point on, have to kill the camera to quit the application.

**Comment by puhitaku** [comment]
Some older camera may have a different way to exchange ISOs in MTP layer.

Adjusting the dial on your camera and choosing "Auto Mode" might solve this issue temporarily. We have no control of ISO in the Auto Mode and the camera adjusts it automatically.

**Comment by puhitaku** [comment]
@wifiuk sorry for inactivity,
Some older camera may have a different way to exchange ISOs in MTP layer.

Adjusting the dial on your camera and choosing "Auto Mode" might solve this issue temporarily. We have no control of ISO in the Auto Mode and the camera adjusts it automatically.

**Comment by puhitaku** [comment]
@wifiuk Ping

**Comment by puhitaku** [comment]
I'll mark this issue outdated and going to close now. Please re-open if the problem persists.
