### ISSUE TITLE
Does not work with D5100

### ISSUE THREAD

**Issue by deemike** [puhitaku/mtplvcap#20]
After installation on Mac OS 10.15, the camera is not recognized by OBS or Skype.

`[0000]  INFO usb: found: 04b0:0429
[0000]  INFO usb: found: 0a12:0001
[0000]  WARN mtp: detected more than 1 device, opening the first device: 04b0:0429
[0000]  INFO main: started

`
`# ./mtplvcap -debug server     
zsh: no such file or directory: ./mtplvcap`

**Comment by puhitaku** [comment]
@deemike Sorry for inactivity,

mtplvcap does not provide a virtual camera but a local HTTP server to serve the frames.

Please read the [Usage](https://github.com/puhitaku/mtplvcap#usage) section to know how to connect mtplvcap and OBS.

Please re-open and mention me if you have additional problems.
