### ISSUE TITLE
D800E does work!!!

### ISSUE THREAD

**Issue by Higomon** [puhitaku/mtplvcap#21]
開発者様

お世話になります。

D800EおよびD7000について
最下部掲載の環境にて無事に動作しましたので、
ご報告いたします。

以前試したD800E → HDMI → キャプチャーカード(Elgato, Cam Link 4K) → Win10
の構成では動作しなかったので諦めていました。ところが、
このソフトを使わせて頂いたことで、全て解決しました。

本当に、感動いたしました。

誠に感謝申し上げます。

### OS
  macOS Big Sur 11.0.1 --> 11.1

### Camera
- D800E
- D7000
 
### App
- OBS 26.1.2(include macOS Virtual Camera)
- Zoom 5.4.9(59931.0110)
- Firefox 84.0.2

**Comment by puhitaku** [comment]
ありがとうございます。ID とともに README に追記させていただきます。ご報告ありがとうございました 👍
