### ISSUE TITLE
Feature: Arch Linux AUR package

### ISSUE THREAD

**Issue by Artiom-M** [puhitaku/mtplvcap#28]
Hi!
Thank you for this wonderful tool! Worked like a charm with D7000.
I've created an AUR package for Arch Linux 
https://aur.archlinux.org/packages/mtplvcap-git/

**Comment by puhitaku** [comment]
@Artiom-M  Oh my god, I'm so proud to see it in AUR! Thank you for using mtplvcap and adding it to AUR!

Since I'm not sure about the AUR nature, let me know how to upgrade the AUR'ed mtplvcap when I pushed the new version. Thanks in advance.

**Comment by Artiom-M** [comment]
AUR is source based packaging system. The package I've created points to your master branch. So each time a user builds the package it takes the latest master.
It can have some drawbacks if your master branch is not stable by your branching strategy. In this case we can consider other options.

2 Apr 2021 01:12:11 Takumi Sueda ***@***.***>:

**Comment by puhitaku** [comment]
> It can have some drawbacks if your master branch is not stable

master branch is considered to be stable so it's not a problem. Thank you for the details!
