### ISSUE TITLE
D500 worked

### ISSUE THREAD

**Issue by yasuoeto** [puhitaku/mtplvcap#29]
D500 

kind | ver
------------ | -------------
model | D500(firmware 1.3.0)
OS | Debian sid(test day is 03/27/2021) 
mtplvcap | 1.2.0 
obs | 26.1.2-290-ga52012e8c(building with browser source) 
zoom  | 5.6.13558.0321

**Comment by puhitaku** [comment]
@yasuoeto Thank you for reporting this! I'll add the info in the README.

**Comment by puhitaku** [comment]
[Added it in the confirmed camera list](https://github.com/puhitaku/mtplvcap/commit/f922398c4ab063c1b8cf973e850f3ee52a90df92). Thanks again and I'm closing this.
