### ISSUE TITLE
D7000 wrong resolution reported

### ISSUE THREAD

**Issue by Artiom-M** [puhitaku/mtplvcap#32]
For D7000 the resolution reported is 4,928 x 3,264 (picture resolution) while actual live view is 640 × 424.
Is this the only possible resolution?
Camera is capable of  1,920 × 1,080 (24p) in video.

**Comment by puhitaku** [comment]
Some older models have quirks that report the original image resolution. The dimension is parsed not from the actual JPEG frame but from Nikon's model-specific header.
Live view has no function to change the resolution, unfortunately.

**Comment by puhitaku** [comment]
While I closed this issue because this problem is a minor and non-critical one, this quirk should be mitigated in some ways like to decide the dimensions by parsing the actual JPEG frames

**Comment by puhitaku** [comment]
I think I'll add a feature like exporting a raw (JPEG + MTP headers) and ask @Artiom-M to upload it. Could you cooperate with me? 😉

**Comment by Artiom-M** [comment]
Sure, I will be happy to help
