### ISSUE TITLE
Higher Resolution?

### ISSUE THREAD

**Issue by NegussugeN** [puhitaku/mtplvcap#34]
Hello,

First of all, the solution is working great with my D3300.  It was simple to connect and provides noticeably less latency that using a capture card.  My one question: Is it possible to achieve higher resolutions using this solution?  Perhaps 720p or even the native 1080p for this camera?

Thanks

**Comment by puhitaku** [comment]
Thanks for using my mtplvcap!

mtplvcap uses the Live View feature. Since this feature is for previewing what the DSLR is seeing, it is not intended to fetch a higher resolution image or even a video stream. There's no way to switch the resolution AFAIK.
