### ISSUE TITLE
mtplvcap for mac M1 not working

### ISSUE THREAD

**Issue by Paolux** [puhitaku/mtplvcap#37]
Hi:
Im trying to use my Nikon d5000 in my new mac mini M1.
When I get to the part of installing the dowloaded zip mtplvcap_macos_amd64.zip I get the attached message.
Also I can't access http://localhost:42839, which would be the camera controller.

I would very appreciate your help since i have not knowledge about coding.

Cheers.

/Users/paolusmac/Downloads/mtplvcap_macos_amd64/mtplvcap ; exit;                
paolusmac@Paoluss-Mac-mini ~ % /Users/paolusmac/Downloads/mtplvcap_macos_amd64/mtplvcap ; exit;
dyld: Library not loaded: /usr/local/opt/libusb/lib/libusb-1.0.0.dylib
  Referenced from: /Users/paolusmac/Downloads/mtplvcap_macos_amd64/mtplvcap
  Reason: image not found
zsh: abort      /Users/paolusmac/Downloads/mtplvcap_macos_amd64/mtplvcap
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by puhitaku** [comment]
Dup: #26 
Please download the `arm64` build and see if it works. Please reopen this issue if the problem persists.
https://github.com/puhitaku/mtplvcap/releases/tag/v1.3.0
