### ISSUE TITLE
Z50 hi-res report

### ISSUE THREAD

**Issue by prg318** [puhitaku/mtplvcap#70]
Hi,
I have a Nikon Z50 with the latest firmware.  I just wanted to report that I'm able to use my Z50 with `mtplvcap -max-resolution` and get 1024x576 video at about 47-50 fps.

I was surprised to achieve this - especially since the Z50 only has a micro USB connector (which I'm assuming is USB 2.x speeds).

Sorry if this is not the right place for this report, but I wanted to pass along the feedback.  Thank you for this project!

**Comment by PulsarFX** [comment]
max-resolution works on my z50, too. 
Latest firmware 2.4 on the camera and linux mint 21.1 as OS with mtplvcap 1.6.1

**Comment by puhitaku** [comment]
Here actually is a right place for reporting this. Thank you all!
