### ISSUE TITLE
Unable to use OBS virtual camera

### ISSUE THREAD

**Issue by tomassasovsky** [puhitaku/mtplvcap#76]
Hello there! First of all, thank you for creating such an awesome piece of software!

I'm having some trouble getting the OBS virtual camera to work on platforms like Google Meet and Zoom. I have a Nikon D5200. Here's my current config:

![image](https://github.com/puhitaku/mtplvcap/assets/63405252/3c681cc6-9297-4a82-ad89-ce54ab5dea90)
![image](https://github.com/puhitaku/mtplvcap/assets/63405252/a6ca31a1-e314-486e-865a-b169086b4dbe)
![image](https://github.com/puhitaku/mtplvcap/assets/63405252/d4a92ae4-6cb1-455c-8b53-ec8262785112)
![image](https://github.com/puhitaku/mtplvcap/assets/63405252/8e4d0e62-173c-46f4-b11b-e8e874b974b7)

Any ideas on what the issue could be here? Thanks again!

**Comment by puhitaku** [comment]
mtplvcap doesn't control virtual cameras which is OS-dependent.
Taking a look at your screenshots, the current video device of Google Meets is "NVID...". It is different from a usual installation of OBS virtual camera's virtual camera service.

**Comment by tomassasovsky** [comment]
Ah, very dumb mistake on my part. Thank you so much for pointing it out for me!
