### ISSUE TITLE
Error installing package

### ISSUE THREAD

**Issue by Bougler** [puhitaku/mtplvcap#83]
[0000] FATAL main: failed to detect MTP devices: could not open 04b0:044f: failed to detach the kernel driver: LIBUSB_ERROR_ACCESS

This is what is shown in terminal when opening the mtplvcap execution

**Comment by Bougler** [comment]
On Mac Studio 2022 with M1 Max Chip

**Comment by Bougler** [comment]
Installed home brew and libusb

**Comment by puhitaku** [comment]
@Bougler Did you run the command with `sudo`?

```
sudo ./mtplvcap
```

**Comment by puhitaku** [comment]
@Bougler ping

**Comment by puhitaku** [comment]
Closing here since the problem should be due to lack of sudo
